### ISSUE TITLE
Dart-sass

### ISSUE THREAD

**Issue by damianof** [regenrek/nuxt-tailwind-postcss-starter#5]
Now that node-sass is being deprecated it would be nice to see your post updated to use dart-sass here
https://regenrek.com/posts/how-to-use-tailwind-css-with-nuxt/#commento-login-box-container

**Comment by regenrek** [comment]
Hi I don't use sass at all. I use postcss for everthing. What you missing?

**Comment by damianof** [comment]
Sorry, meant in your post here in the section "How to use SASS with TailwindCSS + PostCSS"

https://regenrek.com/posts/how-to-use-tailwind-css-with-nuxt/#how-to-use-sass-with-tailwindcss-postcss

I will close this and add a comment on the article. Great article btw, it helped me a lot.

**Comment by regenrek** [comment]
All clear. Probably will mark it as legacy since most of developers use sass (dart-sass seems pretty new). But I prefer postcss so no sass anymore.
